name: Docker Image CI

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  build-server-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build
        run: docker build -f ./Dockerfile -t bergi9/signwriting-fontdb-webservice:latest .
      
      - name: push
        run: docker push bergi9/signwriting-fontdb-webservice:latest
